---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: win2012r2-chef
    driver:
      box: win2012r2-chef
      provider: hyperv
      memory: 2048
      cpus: 2
      network:
        - ["private_network", {bridge: "packer-hyperv-iso"}]


suites:
  - name: default
    run_list:
      - recipe[od-tentacle::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
